title = 'Maxwell Made'
baseURL = 'https://maxwellmade.ca/'
languageCode = 'en-CA'
theme = 'lemur'

[permalinks]
products = "/:slug/"

[menus]
  [[menus.main]]
    name = 'Contact'
    pageRef = '/contact/'
    weight = 30
